In [6]:
import numpy as np
import pandas as pd


data = pd.read_csv("C:\\Users\\Yat\\Documents\\MSDS\\MSDS 7331\\ML_Lab_Data\\listings.csv")

C:\Users\Yat\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (61,62,94,95) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [7]:
sub=data.drop(['id','listing_url','scrape_id','last_scraped','summary','space','description','experiences_offered'
              , 'neighborhood_overview', 'notes', 'transit', 'access', 'interaction', 'house_rules',
              'thumbnail_url', 'medium_url', 'picture_url', 'xl_picture_url', 'host_url', 'host_thumbnail_url',
              'host_picture_url', 'country_code', 'country','amenities', 'minimum_minimum_nights',
              'maximum_minimum_nights','minimum_maximum_nights', 'maximum_maximum_nights','minimum_nights_avg_ntm',
              'maximum_nights_avg_ntm', 'has_availability', 'is_business_travel_ready'], axis=1)
print(sub.columns.values)

['name' 'host_id' 'host_name' 'host_since' 'host_location' 'host_about'
 'host_response_time' 'host_response_rate' 'host_acceptance_rate'
 'host_is_superhost' 'host_neighbourhood' 'host_listings_count'
 'host_total_listings_count' 'host_verifications' 'host_has_profile_pic'
 'host_identity_verified' 'street' 'neighbourhood'
 'neighbourhood_cleansed' 'neighbourhood_group_cleansed' 'city' 'state'
 'zipcode' 'market' 'smart_location' 'latitude' 'longitude'
 'is_location_exact' 'property_type' 'room_type' 'accommodates'
 'bathrooms' 'bedrooms' 'beds' 'bed_type' 'square_feet' 'price'
 'weekly_price' 'monthly_price' 'security_deposit' 'cleaning_fee'
 'guests_included' 'extra_people' 'minimum_nights' 'maximum_nights'
 'calendar_updated' 'availability_30' 'availability_60' 'availability_90'
 'availability_365' 'calendar_last_scraped' 'number_of_reviews'
 'number_of_reviews_ltm' 'first_review' 'last_review'
 'review_scores_rating' 'review_scores_accuracy'
 'review_scores_cleanliness' 'review_scores_checkin'
 'review_scores_communication' 'review_scores_location'
 'review_scores_value' 'requires_license' 'license' 'jurisdiction_names'
 'instant_bookable' 'cancellation_policy' 'require_guest_profile_picture'
 'require_guest_phone_verification' 'calculated_host_listings_count'
 'calculated_host_listings_count_entire_homes'
 'calculated_host_listings_count_private_rooms'
 'calculated_host_listings_count_shared_rooms' 'reviews_per_month']

In [8]:
sub.head()

,name,host_id,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,...,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,Skylit Midtown Castle,2845,Jennifer,2008-09-09,"New York, New York, United States",A New Yorker since 2000! My passion is creatin...,within a few hours,90%,NaN,f,...,NaN,f,strict_14_with_grace_period,t,t,2,1,0,1,0.39
1,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,2008-11-25,"New York, New York, United States",Make Up Artist National/ (Website hidden by Ai...,within a day,100%,NaN,f,...,NaN,f,strict_14_with_grace_period,t,t,1,0,1,0,NaN
2,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,2008-12-07,"New York, New York, United States",Laid-back bi-coastal actor/professor/attorney.,within an hour,90%,NaN,f,...,NaN,f,moderate,f,f,1,1,0,0,4.64
3,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,2009-01-29,"Miami, Florida, United States",I have been a NYer for almost 10 years. I came...,NaN,NaN,NaN,f,...,NaN,f,strict_14_with_grace_period,t,t,1,1,0,0,0.10
4,Large Cozy 1 BR Apartment In Midtown East,7322,Chris,2009-02-02,"New York, New York, United States","I'm an artist, writer, traveler, and a native ...",within a few hours,90%,NaN,f,...,NaN,f,strict_14_with_grace_period,t,t,1,1,0,0,0.60